//ACCESS
export const FETCH_EMBED_FASKES = 'FETCH_EMBED_FASKES';

//FKTP
export const FETCH_MARKER_FKTP = 'FETCH_MARKER_FKTP';
export const FETCH_FKTP_LIST = 'FETCH_FKTP_LIST';
export const FETCH_FKTP_DETAIL = 'FETCH_FKTP_DETAIL';
export const FETCH_FKTP_CABANG = 'FETCH_FKTP_CABANG';

//FKRTL
export const FETCH_MARKER_FKRTL = 'FETCH_MARKER_FKRTL';
export const FETCH_FKRTL_LIST = 'FETCH_FKRTL_LIST';
export const FETCH_FKRTL_DETAIL = 'FETCH_FKTP_DETAIL';
export const FETCH_FKRTL_CABANG = 'FETCH_FKRTL_CABANG';

//FILTER
export const FETCH_CENTER_CABANG = 'FETCH_CENTER_CABANG';
export const FETCH_BBOX_CABANG = 'FETCH_BBOX_CABANG';
export const FETCH_BBOX_KABUPATEN = 'FETCH_BBOX_KABUPATEN';

