//ACCESS
export const FETCH_EMBED_FASKES = 'FETCH_EMBED_FASKES';

//FKTP
export const FETCH_MARKER_FKTP = 'FETCH_MARKER_FKTP';
export const FETCH_FKTP_LIST = 'FETCH_FKTP_LIST';
export const FETCH_FKTP_DETAIL = 'FETCH_FKTP_DETAIL';
export const FETCH_FKTP_CABANG = 'FETCH_FKTP_CABANG';
export const FETCH_FKTP_KEDEPUTIAN = 'FETCH_FKTP_KEDEPUTIAN';

//FKRTL
export const FETCH_MARKER_FKRTL = 'FETCH_MARKER_FKRTL';
export const FETCH_FKRTL_LIST = 'FETCH_FKRTL_LIST';
export const FETCH_FKRTL_DETAIL = 'FETCH_FKTP_DETAIL';
export const FETCH_FKRTL_CABANG = 'FETCH_FKRTL_CABANG';
export const FETCH_FKRTL_KEDEPUTIAN = 'FETCH_FKRTL_KEDEPUTIAN';

//LIST
export const FETCH_JENIS_FKTP = 'FETCH_JENIS_FKTP';
export const FETCH_JENIS_FKRTL = 'FETCH_JENIS_FKRTL';
export const FETCH_CANGGIH = 'FETCH_CANGGIH';

//FILTER
export const FETCH_CENTER_CABANG = 'FETCH_CENTER_CABANG';
export const FETCH_BBOX_CABANG = 'FETCH_BBOX_CABANG';
export const FETCH_CENTER_KEDEPUTIAN = 'FETCH_CENTER_KEDEPUTIAN';
export const FETCH_BBOX_KEDEPUTIAN = 'FETCH_BBOX_KEDEPUTIAN';
export const FETCH_BBOX_KABUPATEN = 'FETCH_BBOX_KABUPATEN';

export const FETCH_AUTO_WILAYAH = 'FETCH_AUTO_WILAYAH';
export const FETCH_WILAYAH_ADMIN = 'FETCH_WILAYAH_ADMIN';
export const FETCH_ADMIN_CANGGIH = 'FETCH_ADMIN_CANGGIH';

export const FETCH_FILTER_FKTP = 'FETCH_FILTER_FKTP';
export const FETCH_FILTER_FKRTL = 'FETCH_FILTER_FKRTL';

export const FETCH_FILTER_FKTP_LIST = 'FETCH_FILTER_FKTP_LIST';
export const FETCH_FILTER_FKRTL_LIST = 'FETCH_FILTER_FKRTL_LIST';


export const FETCH_COUNT_FKTP = 'FETCH_COUNT_FKTP';
export const FETCH_COUNT_FKRTL = 'FETCH_COUNT_FKRTL';

